[build]
publish = "dist"
command = "npx vite build"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/"
to = "/booking.html"
status = 200

[[redirects]]
from = "/*"
to = "/booking.html"
status = 200